#!/usr/bin/env bash
cd ..
sudo apt install make build-essential default-jre default-jdk
git clone https://github.com/5x5x5x5/craftinginterpreters
cd craftinginterpreters
wget https://storage.googleapis.com/dart-archive/channels/stable/release/latest/linux_packages/dart_2.19.2-1_amd64.deb
sudo dpkg -i dart_2.19.2-1_amd64.deb
export PATH="$PATH:/usr/lib/dart/bin"
make get
make
cd ../dlox
